version: '2'
services:
  web:
    container_name: web
    image: "realpac/flask-app:$TAG"
    ports:
    - "5000:5000"
  frontend:
    image: "realpac/ng-app:$TAG"
    depends_on:
      - web
    ports:
    - "80:80"
